# Generated by Django 4.2.7 on 2023-11-23 16:10

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Day',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('awoke', models.TimeField(null=True)),
                ('sunnah_duration', models.IntegerField(blank=True, null=True)),
                ('sleep', models.TimeField(blank=True, null=True)),
                ('education_time', models.IntegerField(blank=True, null=True)),
                ('din_ed_time', models.IntegerField(blank=True, null=True)),
                ('azkar_subh', models.BooleanField(blank=True)),
                ('azkar_asr', models.BooleanField(blank=True)),
                ('quran_str', models.IntegerField(blank=True, null=True)),
                ('masjeed', models.IntegerField(blank=True, null=True)),
                ('work_time', models.IntegerField(blank=True, null=True)),
                ('problem', models.BooleanField()),
                ('youtube_time', models.IntegerField(blank=True, null=True)),
                ('happy_level', models.IntegerField(choices=[(0, '0'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100')])),
                ('difficult_work', models.IntegerField(choices=[(0, '0'), (10, '10'), (20, '20'), (30, '30'), (40, '40'), (50, '50'), (60, '60'), (70, '70'), (80, '80'), (90, '90'), (100, '100')])),
                ('date', models.DateField(auto_now=True)),
            ],
        ),
    ]
