# Generated by Django 4.2.7 on 2023-11-25 14:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='work_time',
            new_name='work_time_pc',
        ),
        migrations.AddField(
            model_name='day',
            name='work_time_wash',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='day',
            name='date',
            field=models.DateField(),
        ),
    ]
