# Generated by Django 4.2.7 on 2023-11-27 08:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0003_day_anxiety_day_money_from_pc_day_money_from_wm'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='sport',
            field=models.BooleanField(default=False),
        ),
    ]
