# Generated by Django 4.2.7 on 2023-11-28 05:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0004_day_sport'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='weekend',
            field=models.BooleanField(default=False),
        ),
    ]
