# Generated by Django 4.2.7 on 2023-11-30 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0005_day_weekend'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='soum',
            field=models.BooleanField(default=False),
        ),
    ]
