# Generated by Django 4.2.7 on 2023-12-04 06:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0006_day_soum'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='apathy_to_work',
            field=models.BooleanField(default=False),
        ),
    ]
