# Generated by Django 4.2.7 on 2023-12-05 09:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0008_rename_apathy_to_work_day_apathy_w_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='day',
            name='salat',
            field=models.BooleanField(default=False),
        ),
    ]
