# Generated by Django 4.2.7 on 2023-12-07 06:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0010_rename_azkar_asr_day_az_asr_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='day',
            name='problem',
        ),
        migrations.AddField(
            model_name='day',
            name='dont_watch',
            field=models.BooleanField(default=False, verbose_name='просм.'),
        ),
        migrations.AddField(
            model_name='day',
            name='dua',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='looked_down',
            field=models.BooleanField(default=False, verbose_name='пот.взор'),
        ),
        migrations.AddField(
            model_name='day',
            name='tauba',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='day',
            name='tg',
            field=models.BooleanField(default=False),
        ),
    ]
