# Generated by Django 4.2.7 on 2023-12-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0014_alter_day_dont_watch_alter_day_looked_down_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='day',
            name='dont_watch',
            field=models.BooleanField(verbose_name='Не см.харам'),
        ),
        migrations.AlterField(
            model_name='day',
            name='looked_down',
            field=models.BooleanField(verbose_name='Потуп.взор'),
        ),
    ]
