# Generated by Django 4.2.7 on 2023-12-07 18:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mujahid_app', '0015_alter_day_dont_watch_alter_day_looked_down'),
    ]

    operations = [
        migrations.RenameField(
            model_name='day',
            old_name='quran_str',
            new_name='quran',
        ),
        migrations.AlterField(
            model_name='day',
            name='dont_watch',
            field=models.BooleanField(verbose_name='Не см.'),
        ),
        migrations.AlterField(
            model_name='day',
            name='looked_down',
            field=models.BooleanField(verbose_name='Пот.взор'),
        ),
    ]
